site_name: Realistic Subnautica ModPack # ← Название вашего сайта
site_url: https://dimas-petrov.github.io/Realistic-Subnautica-ModPack/

theme:
  name: material
  language: ru
  palette:

    # Светлая тема
    - scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

    # Тёмная тема (стандартная)
    # - scheme: slate
    #   primary: blue
    #   accent: light-blue
    #   toggle:
    #     icon: material/weather-night
    #     name: Тёмная тема

    # AMOLED-тема (максимально тёмная встроенными средствами)
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night
        name: Тёмная тема
# theme:
#   name: material
#   language: ru
#   palette:
#     - scheme: default
#       primary: blue
#       accent: light-blue
#       toggle:
#         icon: material/weather-night
#         name: Переключить на AMOLED-тему

#     - scheme: slate
#       primary: black
#       accent: white
#       toggle:
#         icon: material/weather-sunny
#         name: Переключить на тёмную тему

#     - scheme: amoled
#       primary: black
#       accent: 
#       toggle:
#         icon: material/moon-waning-crescent
#         name: Переключить на светлую тему
# extra_css:
#   - stylesheets/extra.css
  
nav:
  - Главная: index.md
  - Установка: Installation.md
  - ЧаВо: faq.md

markdown_extensions:
  - admonition # Красивые блоки "Важно", "Подсказка"
  - pymdownx.details # Сворачиваемые блоки
  - pymdownx.superfences # Расширенные возможности для кода
  - pymdownx.tabbed: # Контент в виде вкладок
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html