site_name: Realistic Subnautica ModPack
site_url: https://dimas-petrov.github.io/Realistic-Subnautica-ModPack/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicons/favicon-32x32.png
  logo: assets/favicons/apple-touch-icon.png
  language: ru
  palette:
    # Светлая тема
    - scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Светлая тема

    # Тёмная тема
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/weather-night
        name: Тёмная тема

    # AMOLED тема (чисто чёрный фон)
    - scheme: amoled
      primary: black
      accent: white
      toggle:
        icon: material/circle-half-full
        name: AMOLED тема

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocs-video
  - awesome-pages

extra:
  consent:
    title: Cookie consent
    description: >
      Мы используем файлы cookie, чтобы улучшить работу сайта.
    actions:
      - accept
      - reject
      - manage
    cookies:
      github:
        name: GitHub
        checked: true

copyright: >
  © 2026 Realistic Subnautica ModPack. 
  <a href="/privacy-policy/">Политика конфиденциальности</a> | 
  <a href="/terms-of-service/">Условия использования</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html