name: Deploy MkDocs site to Pages
on:
  push:
    branches: ["main"] # ваша главная ветка (main или master)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5   # обновлено
      - uses: actions/setup-python@v6 # обновлено
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and Deploy
        run: mkdocs gh-deploy --force